### ISSUE TITLE
Problems With Dockerfile

### ISSUE THREAD

**Issue by ghost** [johnpapa/one-with-angular#10]
Tried your docker files but had some issues. First, default installation of docker-compose didn't work with version 2.1. Then, got an error with the AS part of your FROM statements in the dockerfile. Then, after removing those, got an error
```
Step 7 : RUN ng build --prod
 ---> Running in 8c7d943233cd
An asset cannot be written to a location outside of the output path.
ERROR: Service 'one-with-angular' failed to build: The command '/bin/sh -c ng build --prod' returned a non-zero code: 1
```

**Comment by ghost** [comment]
resolved -- requires docker 1.17 or higher

**Comment by pointtoken** [comment]
Upgrading to docker resolved the compose issues, but I'm still getting this error:
```
Step 7 : RUN ng build --prod
 ---> Running in 8c7d943233cd
An asset cannot be written to a location outside of the output path.
ERROR: Service 'one-with-angular' failed to build: The command '/bin/sh -c ng build --prod' returned a non-zero code: 1
```

**Comment by ghost** [comment]
Upgrading everything to latest versions (angular cli, node, etc) fixed this
